apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-original
  labels:
    app: netflix-original
spec:
  replicas: 10
  selector:
    matchLabels:
      app: netflix-original
  template:
    metadata:
      labels:
        app: netflix-original
    spec:
      containers:
      - name: netflix-original
        image: gauri839/netflix:latest
        ports:
        - containerPort: 80
